spring:
  application:
    name: eureka-server
server:
  port: 8888

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone:  http://192.168.0.222:8888/eureka/
  instance:
    prefer-ip-address: true
  server:
    enableSelfPreservation: false






