ipAddress:
  client: 192.168.0.222
  redis: 192.168.0.222
  eureka: 192.168.0.222
  mysql: bj-cdb-0srt3yo9.sql.tencentcdb.com
server:
  port: 8802
spring:
  profiles:
    active: dev
  datasource:
    master:
      url: jdbc:mysql://${ipAddress.mysql}:63422/dev_master_pomr?characterEncoding=utf-8
      username: root
      password: Qlxlm123456
      driver-class-name: com.mysql.jdbc.Driver
    slaver:
      url: jdbc:mysql://${ipAddress.mysql}:63422/dev_master_pomr?characterEncoding=utf-8
      username: root
      password: Qlxlm123456
      driver-class-name: com.mysql.jdbc.Driver
  cloud:
    discovery:
      enabled: true
      serviceId: eureka-server
    client:
      ipAddress: ${ipAddress.client}
  redis:
  #################redis基础配置#################
    database: 8
    host: ${ipAddress.client}
    password:
    port: 6379
    timeout: 5000
  #################redis线程池设置#################
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-active: 2000
        max-wait: 1000

eureka:
  client:
    serviceUrl:
      defaultZone:  http://${ipAddress.client}:8888/eureka/
  instance:
      preferIpAddress: true
      instance-id: ${spring.cloud.client.ipAddress}:${server.port}
feign:
  hystrix:
    enabled: true
ribbon:
  ReadTimeout: 40000
  ConnectTimeout: 40000
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 40000
  threadpool:
      default:
        coreSize: 10
logging:
  level:
    root: debug