server:
  port: 80
spring:
  profiles:
    active: dev
  cloud:
    discovery:
      enabled: true
      serviceId: eureka-server
    client:
      ipAddress: 172.18.9.173
  redis:
  #################redis基础配置#################
    database: 8
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 5000
  #################redis线程池设置#################
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-active: 2000
        max-wait: 1000
eureka:
  client:
    serviceUrl:
      defaultZone:  http://172.18.9.173:8888/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
zuul:
  routes:
    api-a:
      path: /api-user/**
      service-id: user-server
    api-b:
      path: /api-third/**
      service-id: third-server
    api-c:
      path: /api-stata/**
      service-id: stata-server
    api-d:
      path: /api-record/**
      service-id: record-server
    api-e:
      path: /api-assessmen/**
      service-id: assessmen-server
    api-f:
      path: /api-order/**
      service-id: order-server
    api-g:
      path: /api-wallet/**
      service-id: wallet-server
    api-h:
      path: /api-goods/**
      service-id: goods-server
    api-i:
      path: /api-archive/**
      service-id: archive-server
    api-j:
      path: /api-statistic/**
      service-id: statistic-server
    api-qlxlm:
      path: /
      url: http://www.qlxlm.com
    api-qlxlm2:
      path: /aa
      url: file:///prostaticUnion/index.html
    api-qlxlm3:
      path: /aaa
      url: file://prostaticUnion/index.html
ribbon:
  ReadTimeout: 40000
  ConnectTimeout: 40000
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 1600000


